### ISSUE TITLE
a question about preprocess_depparse.py

### ISSUE THREAD

**Issue by fudanchenjiahao** [clarkkev/attention-analysis#1]
In readme ,I can see  ''Each line in the files should contain a word followed by a space followed by <index_of_head>-<dependency_label> (e.g., 0-root).''

So how can I get the index_of_head, and what's the meaning of it?

Should I know which heads(12*12) in bert is for which syntactic function firstly ,and then judge it?
Sorry for my pool English.

**Comment by clarkkev** [comment]
Here "head" refers to the [syntactic head](https://en.wikipedia.org/wiki/Head_(linguistics)) of the word, not an attention head of BERT. For example, if you were using [CoNLL-U](https://universaldependencies.org/format.html) data, the head would be given as the seventh field of the line (you would have to write a script to convert the data from CoNLL-U to the simpler format we use). If you don't have access to Penn Treebank data, you could use data from [Universal Dependencies](https://universaldependencies.org/), which is public.
