### ISSUE TITLE
How to deal with the OOV words

### ISSUE THREAD

**Issue by BrambleXu** [clarkkev/attention-analysis#2]
My sample contains the word 'Silsby', but it does not exist in the vocab. 
How to deal with the OOV situation?

```
python extract_attention.py --preprocessed-data-file samples_10.json --bert-dir data/cased_L-12_H-768_A-12  --max_sequence_length 256 --word_level --cased

Creating examples...
Traceback (most recent call last):
  File "extract_attention.py", line 144, in <module>
    main()
  File "extract_attention.py", line 108, in main
    example = Example(features, tokenizer, args.max_sequence_length)
  File "extract_attention.py", line 29, in __init__
    self.input_ids = tokenizer.convert_tokens_to_ids(self.tokens)
  File "/Users/smap10/Project/attention-analysis-master/bert/tokenization.py", line 182, in convert_tokens_to_ids
    return convert_by_vocab(self.vocab, tokens)
  File "/Users/smap10/Project/attention-analysis-master/bert/tokenization.py", line 143, in convert_by_vocab
    output.append(vocab[item])
KeyError: 'Silsby'
```

**Comment by clarkkev** [comment]
Are you passing in your data using the key "words" in your json? If so, the script should run BERT tokenization for you (see [here](https://github.com/clarkkev/attention-analysis/blob/master/extract_attention.py#L27)). But if you are instead passing in the data using the key "tokens," the script assumes the data is already BERT-tokenized (i.e., each token is in the vocab).

**Comment by BrambleXu** [comment]
I pass the data using the key "tokens", which is already BERT-tokenized

**Comment by clarkkev** [comment]
In that case you should only pass in "words", not both "words" and "tokens". Sorry for the confusion!

**Comment by BrambleXu** [comment]
Can I only pass the "tokens"?

**Comment by clarkkev** [comment]
Sure, but then you can't get word-level attention. Passing in both "words" and "tokens" is redundant because the words you pass in get tokenized automatically.

**Comment by BrambleXu** [comment]
Understood, thanks!
