### ISSUE TITLE
An explanation for head_distances.py

### ISSUE THREAD

**Issue by tomohideshibata** [clarkkev/attention-analysis#5]
Thank you for releasing the codes.

An explanation for `head_distances.py` is missing in README.
Could you add the explanation?

A small question: in `head_distances.py`, the line `utils.write_pickle(js_distances, args.outfile)` should be outside the "for loop" `for i, doc in enumerate(data):`?

**Comment by clarkkev** [comment]
Sure, I added an explanation! It would be a tiny bit more efficient to have `utils.write_pickle(js_distances, args.outfile)` outside of the loop so the distances are only written to disk once. I put it in the loop however so you can halt the program at any time and still have data to work with.

**Comment by tomohideshibata** [comment]
Thank you for your response! I understand the reason for `write_pickle`.
