### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by imr555** [clarkkev/attention-analysis#6]
First of I want to say this is a great insight into the BERT model. But there seems to be a file missing from General Analysis. The file as said can be used to generate one's own wiki data. 
(create_wiki_data.py). It would be quite helpful if you provide it .

**Comment by clarkkev** [comment]
Oops, that comment is out-of-date. You can use `preprocess_unlabeled.py` and `extract_attention.py` to create your own data files (see the README for details).

**Comment by imr555** [comment]
Thank You very Much 😊
