### ISSUE TITLE
for extract attention --word_level attention doesnt work 

### ISSUE THREAD

**Issue by ManasiPat** [clarkkev/attention-analysis#7]
I have used preprocess_unlabelled to create my json file. Can you provide a preprocess file which would help word level attention.

When I use this file and when I pass the argument --word_level to extract_attention I get the following error:
Converting to word-level attention...
Traceback (most recent call last):
  File "extract_attention.py", line 144, in <module>
    main()
  File "extract_attention.py", line 134, in main
    feature_dicts_with_attn, tokenizer, args.cased)
  File "/home/manasi/Documents/BERT/attention-analysis-master/bpe_utils.py", line 74, in make_attn_word_level
    words_to_tokens = tokenize_and_align(tokenizer, features["words"], cased)
KeyError: 'words'

Please help me fix it.

**Comment by clarkkev** [comment]
As the README says, you need to supply "words" as opposed to "text" or "tokens" in the data json to get word-level attention.

**Comment by gump88** [comment]
@clarkkev 
Should I supply "words" by additional code? I did not see code doing this in preprocess_unlabelled.py.

Thanks!
