### ISSUE TITLE
While extracting attention weights, set segment_ids all zeros ?

### ISSUE THREAD

**Issue by HuXiangkun** [clarkkev/attention-analysis#9]
The code in this line means set segment ids to zeros for both segments, I don't know whether this is a bug?

https://github.com/clarkkev/attention-analysis/blob/7b4ed20b2c58a211970ffc19c2d957b2c35ea0ea/extract_attention.py#L30

**Comment by clarkkev** [comment]
It is pretty normal to finetune BERT with a single segment of [CLS]<text>[SEP]. For most tasks there aren't really two segments (e.g., dependency parse examples are a single sentence) so it is fine. But yes, it may have been better to set the segment ids as 0 for the first segment and 1 for the next for our unlabeled data analysis.
